#!/bin/sh

DIALOG=zenity

tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --list \
  --title="Установка программ" \
  --column="Выбор" --column="Название" --column="Описание" \
    1 onlyoffice-bin "GtkTreeView crashes on multiple selections" \
    2 1C "GNOME Dictionary does not handle proxy" \
    3 rambox-bin "Menu editing does not work in GNOME 2.0" --checklist 1> $tempfile

    retval=$?


grep '|' -P -R -I -l $tempfile | xargs sed -i 's/|/ /g'

    choice=`cat $tempfile`


if [ "$choice" == "$choice" ]; then

sudo emerge $choice |

      zenity --text-info \
          --title="Установка $choice"
  
	
        if [ "$?" = -1 ] ; then
                zenity --error \
                  --text="Установка отменена."
			
        fi
fi

