#!/bin/sh

DIALOG=zenity

tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --list \
  --title="Установка программ" \
  --column="Выбор" --column="Название" --column="Описание" \
    	1 1C "1С Предприятие" \
	2 onlyoffice-bin "ONLYOFFICE — офисный пакет с открытым исходным кодом" \
    	3 rambox-bin "Rambox - это браузер рабочей области" --checklist 1> $tempfile

    retval=$?


grep '|' -P -R -I -l $tempfile | xargs sed -i 's/|/ /g'

    choice=`cat $tempfile`


if [ "$choice" == "$choice" ]; then

sudo emerge $choice |

zenity --progress --text="Идет установка программ $choice ... ждите" --pulsate


#      zenity --text-info \
#          --title="Установка $choice"
  
	
        if [ "$?" = -1 ] ; then
                zenity --error \
                  --text="Установка отменена."
			
        fi
fi

