#!/bin/sh

dirprograms=`ls ~ | grep Programs`

	if [ dirprograms != $dirprograms ]; then
	    echo "Папка Programs есть в каталоге"
	    else
 	    mkdir ~/Programs
        fi

#путь путь до текстовых файлов
#pathtextfile=/usr/share/linuxbuh-installer/txt
pathtextfile=./txt

text="Нажите Да и будет скачана и установленна программа\nи необходимые для нее библиотеки\n"
text1="Все установленно!\n\n Приятной и продуктивной Вам работы"
text2="Идет установка!\n\n Ждите zenity"


    if [ "$DISPLAY" != "" ];
    then
        DIALOG="dialog"
    else
        DIALOG="dialog"
    fi


tempfile=`mktemp 2>/dev/null` || tempfile=/tmp/test$$
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --list \
  --title="Установка программ" \
  --column="Выбор" --column="Название" --column="Описание" \
    1 Onlyoffice "GtkTreeView crashes on multiple selections" \
    2 1C "GNOME Dictionary does not handle proxy" \
    3 Rambox "Menu editing does not work in GNOME 2.0" --checklist 1> $tempfile

    retval=$?

    choice=`cat $tempfile`

if [ "$choice" == "Onlyoffice" ]; then

sudo emerge -av onlyoffice-bin

fi

############################ 1C_Enterprise


